export const GAMES = {
  SOCCER: 'SOCCER',
  SNAKE: 'SNAKE',
};

export const CONTROLLERS = {
  [GAMES.SOCCER]: 'GAMEPAD',
  [GAMES.SNAKE]: 'DPAD',
};

export const EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_JOINED: 'ROOM_JOINED',
  ERROR: 'ERROR',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  INPUT: 'INPUT',
  GAME_UPDATE: 'GAME_UPDATE',
  SELECT_GAME: 'SELECT_GAME',
  GAME_CHANGED: 'GAME_CHANGED',
  START_GAME: 'START_GAME',
  PAUSE_GAME: 'PAUSE_GAME',
  RESTART_GAME: 'RESTART_GAME',
  ADD_TIME: 'ADD_TIME',
  SUB_TIME: 'SUB_TIME',
  GOAL_SCORED: 'GOAL_SCORED',
  GET_GAME_STATE: 'GET_GAME_STATE',
  GAME_STATE: 'GAME_STATE',
  SIGNAL: 'SIGNAL',
};

export const INPUT_TYPES = {
  JOYSTICK: 0,
  BUTTON_DOWN: 1,
  FIRE_SHOT: 2,
  DPAD: 3,
};

export const INPUT_MAP = {
  // Buttons
  A: 0,
  B: 1,
  POWER: 2,
  // Directions
  UP: 3,
  DOWN: 4,
  LEFT: 5,
  RIGHT: 6,
};
